### ISSUE TITLE
July Pull Requests Merge Conflicts

### ISSUE THREAD

**Issue by jonasppsi** [paulscherrerinstitute/PsiIpPackage#19]
Hallo @obruendl , @paedu92 

Ich hatte ein paar Merge Conflicts bei den Pull Requests. Folgende Abschnitte waren betroffen:

https://github.com/paulscherrerinstitute/PsiIpPackage/blob/b004e007288b59d018ca9076d2de0fe0438daca5/IpPackage2017_2_1.tcl#L47-L48

https://github.com/paulscherrerinstitute/PsiIpPackage/blob/b004e007288b59d018ca9076d2de0fe0438daca5/IpPackage2017_2_1.tcl#L1054

https://github.com/paulscherrerinstitute/PsiIpPackage/blob/b004e007288b59d018ca9076d2de0fe0438daca5/IpPackage2017_2_1.tcl#L843-L905

Ich habe die entsprechenden Zeilen behalten und hoffe bei euch funktionierts noch. Habe bei meinem Package kein Problem festgestellt, nutze aber auch nicht die neuen Features...

Gruss,
Jonas

**Comment by paedu92** [comment]
Hallo @jonasppsi 

Danke für das Einbinden meiner Vorschläge!
Der 1. und 3. Konflikt ist behalten richtig.
Beim 2. hätte man die Zeile löschen können -> werden nun schon weiter oben aufgerufen, doch schaden tut sie nicht.

Ich werde das neue Release bald verwenden und testen (in ca. 2 Wochen).
Falls es dann noch etwas "aufzuräumen" gibt würde ich einen neuen Commit ablegen.

Gruss Patrick
