### ISSUE TITLE
Bug: Remove default xgui file

### ISSUE THREAD

**Issue by paedu92** [paulscherrerinstitute/PsiIpPackage#23]
If IP_NAME and IP_TOP_ENTITY are equal, then the script will delete the "real" xgui file instead of the old one.
(Because they are equal)

To solve the bug, we have to test if the $OldXguiFile != $NewXguiFile before we remove it.

I will place a pull-request.

**Comment by jonasppsi** [comment]
Thanks. Has been merged a while ago. Closing issue.
